# Browsersync port
PORT: 8080

# Gulp path references
PATHS:
  # Path to "docs" folder
  docs: docs
  # Paths to Sass libraries, which can then be loaded with @import
  # without the need for the full path "node_modules/.." everytime
  sassLibs:
    - node_modules/foundation-sites/scss
    - node_modules/motion-ui/src
    - node_modules/bootstrap/scss
    - node_modules/uikit/src/scss
  # Path to static assets & ignore some folders
  assets:
    - "src/assets/**/*"
    - "!src/assets/root/**/*"
    - "!src/assets/{img,js,scss}/**"
  images:
    - "src/assets/**/*.{jpg,jpeg,png,gif,svg,webp}"
    - "!src/assets/root/**/*"
    - "!src/assets/fonts/**"
  # Path to static files to copy to "docs"
  staticFiles:
    - "src/robots.txt"
    - "src/favicon.ico"
    - "src/.htaccess"
    - "src/site.webmanifest"
  rootFiles:
    - "src/assets/root/**/*"
